name: CI

on: [push, workflow_dispatch]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.21.x"
                  cache: false
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21.x"
            - name: Build
              run: go build -v ./
            - name: Test
              run: go test
